app            = 'test-fly-ssh'
primary_region = 'ams'

[build]

[[services]]
  internal_port        = 2222
  protocol             = 'tcp'
  auto_stop_machines   = true
  auto_start_machines  = true
  min_machines_running = 0
  processes            = ['app']
  [[services.ports]]
    port = 22

[[vm]]
  memory   = '1gb'
  cpu_kind = 'shared'
  cpus     = 1
